series:
  television-list:
    - "Baby Daddy"
    - "Babylon 5"
    - "Babylon Berlin"
    - "Back"
    - "Back to the Future"
    - "Backstrom"
    - "Bad Blood"
    - "Bad Blood (2017)"
    - "Bad Education":
        set:
          tvdb_id: 261277
    - "Bad Move"
    - "Ballers"
    - "Balls Deep"
    - "Bam's Unholy Union"
    - "Banana Fish"
    - "Bancroft"
    - "Band of Brothers"
    - "Bankerot":
        set:
          tvdb_id: 287105
    - "Banshee"
    - "Barbarians Rising"
    - "Baroness Von Sketch Show"
    - "Barry"
    - "Baskets"
    - "The Bastard Executioner"
    - "Bates Motel":
        set:
          tvdb_id: 262414
    - "Batman":
        alternate_name:
          - "Batman (1966)"
        set:
          tvdb_id: 77871
    - "The Batman"
    - "Batman: The Animated Series":
        set:
          tvdb_id: 76168
    - "Battle Creek"
    - "Battlestar Galactica 1978"
    - "Battlestar Galactica 2003"
    - "Battlestar Galactica 2004"
    - "Baywatch"
    # - "The BBC at War"
    - "Be Cool Scooby-Doo!"
    - "Bear Grylls: Survival School"
    - "Beast Wars"
    - "Beat Bugs"
    - "Beauty and the Beast 2012"
    - "The Beauty Inside"
    - "The Beaverton"
    - "Beavis and Butthead"
    - "Becoming Human"
    - "Beetle Juice"
    - "Being Erica"
    - "Being Human (2008)":
        alternate_name:
          - "Being Human UK"
    - "Being Mary Jane":
        set:
          tvdb_id: 268872
    - "Believe"
    - "Bellevue"
    - "Ben 10"
    - "Benders"
    - "Benidorm":
        set:
          tvdb_id: 79912
    - "Bennington Gothique"
    - "Bent"
    - "Beowulf: Return to the Shieldlands"
    - "Berlin Station"
    - "Betas"
    - "Better Call Saul":
        alternate_name:
          - "Лучше звоните Солу"  # Russian
        set:
          tvdb_id: 273181
    - "Better Late Than Never"
    - "Better Things"
    - "Between"
    - "Between Two Ferns with Zach Galifianakis"
    - "Beyond":
        set:
          tvdb_id: 318106
    - "Beyond Belief: Fact or Fiction"
    - "Beyond Reality"
    - "The Big Bang Theory":
        set:
          tvdb_id: 80379
    - "Big Cats"
    - "Big Hero 6 the Series"
    - "Big Little Lies":
        set:
          tvdb_id: 305719
    - "Big Mouth"
    - "Big Pacific"
    - "Big School"
    - "Bill Nye Saves the World":
        set:
          tvdb_id: 323843
    - "Bill Nye the Science Guy"
    - "Billions":
        set:
          tvdb_id: 279536
    - "Billy and Billie"
    - "Bionic Woman"
    - "Birds of a Feather"
    - "Bite Club"
    - "Bizaardvark"
    - "Black Books"
    - "The Black Donnellys"
    - "Black Dynamite"
    - "Black Earth Rising"
    - "Black Jesus"
    - "Black Lake":
        alternate_name:
          - "Svartsjön"
    - "Black Lightning"
    - "Black Mirror"
    - "Black Sails":
        alternate_name:
          - "Черные паруса"  # Russian
        set:
          tvdb_id: 262407
    - "Black Scorpion"
    - "Black-ish"
    - "Blackadder"
    - "The Blacklist":
        set:
          tvdb_id: 266189
    - "The Blacklist: Redemption":
        set:
          tvdb_id: 311903
    - "Blackstone"
    - "Blackwork"
    - "Blade: The Series"
    - "Blaze and the Monster Machines"
    - "Blindspot":
        set:
          tvdb_id: 295647
    - "Blood Drive"
    - "Blood Ties"
    - "Bloodline":
        set:
          tvdb_id: 287314
    - "Bloom"
    - "Blue Bloods":
        set:
          tvdb_id: 164981
    - "Blue Collar TV"
    - "Blue Heelers"
    - "Blue Mountain State"
    - "Blue Planet II"
    - "Blue Water High"
    - "Blues Clues"
    - "Bluestone 42"
    - "Boardwalk Empire"
    - "The Boat"
    - "Bobs Burgers"
    - "Bodyguard"
    - "Bojack Horseman"
    - "The Bold Type"
    - "Bomb Girls"
    - "The Boondocks"
    - "The Booth at the End"
    - "Bonanza"
    - "Bones":
        alternate_name:
          - "Кости"  # Russian
        set:
          tvdb_id: 75682
    - "Bong Appetit"
    - "Borderline (2016)"
    - "Bored to Death"
    - "Border Patrol"
    - "Borderline"
    - "Borgia"
    - "Born to Kill (2017)"
    - "Bosch"
    - "Botched"
    - "Bottom"
    - "Boundless"
    - "Bounty Hunters (2017)"
    - "The Brady Bunch"
    - "Braindead"
    - "Braquo"
    - "The Brave"
    - "Breaking Bad"
    - "Breaking In"
    - "Breathe"
    - "Brickleberry"
    - "The Bridge"
    - "The Bridge (2013)"
    - "Bridget and Eamon"
    - "The Brighton Police"
    - "Britannia"
    - "Broad City"
    - "Broadchurch":
        set:
          tvdb_id: 266398
    - "Brockmire"
    - "Broken"
    - "Brooklyn Nine-Nine"
    - "Brothers and Sisters"
    - "Buck Rogers in the 25th Century"
    - "Bucket"
    - "Bucky O'Hare and the Toad Wars!"
    - "Budding Prospect":
        set:
          tvdb_id: 000000  # FIXME: Not yet added
    - "Buddy Thunderstruck"
    - "Buffy the Vampire Slayer"
    - "Building Off the Grid"
    - "Bull"
    - "Bullet in the Face"
    - "Burden of Truth"
    - "The Bureau":
        alternate_name:
          "Le Bureau des Legendes"
    - "Butterfly"
    - "Buzz Lightyear of Star Command"
