series:
  television-list:
    - "Cable Girls"
    - "Californication"
    - "Call Me Fitz"
    - "Call My Agent!":
        alternate_name:
          - "Dix pour cent"
    - "Call the Midwife"
    - "Camelot"
    - "Camping":
        alternate_name:
          "Camping US"
    - "Cannabis"
    - "Can't Cope, Won't Cope"
    - "Canterburys Law"
    - "The Cape"
    - "Caprica"
    - "Captain Planet and the Planeteers"
    - "Captain Scarlet and the Mysterons"
    - "Captive"
    - "The Carbonaro Effect"
    - "Cardinal"
    - "Carl's Pissed"
    - "The Carmichael Show"
    - "Carnivale"
    - "Carter"
    - "Carter's Get Rich"
    - "Case"
    - "The Case: Book of Sherlock Holmes"
    - "Castle"
    - "Castle Rock"
    - "Castlevania"
    - "Casual"
    - "Catastrophe (2015)"
    - "The Catch":
        set:
          tvdb_id: 295696
    - "Catdog"
    - "Caught"
    - "Cavendish"
    - "Champaign Ill"
    - "Chance"
    - "Channel Zero":
        set:
          tvdb_id: 315178
    - "El Chapo"
    - "Chappelle's Show"
    - "Charlie's Angels"
    - "Charmed"
    - "Chasing Classic Cars":
        set:
          tvdb_id: 172181
    - "Chasing Life"
    - "Chasing Shadows"
    - "Cheers"
    - "Chemistry"
    - "Chemistry: A Volatile History"
    - "Chesapeake Shores"
    - "Chewing Gum":
        set:
          tvdb_id: 301562
    - "The Chi"
    - "Chicago Fire":
        set:
          tvdb_id: 258541
    - "Chicago Justice":
        set:
          tvdb_id: 311896
    - "Chicago Med":
        set:
          tvdb_id: 295640
    - "Chicago PD":
        set:
          tvdb_id: 269641
    - "Chico and the Man"
    - "Childhoods End"
    - "Children of Dune"
    - "Children of Fire Mountain"
    - "Chillers"
    - "Chilling Adventures of Sabrina"
    - "Chilly Willy"
    - "Chip n Dale: Rescue Rangers"
    - "CHiPs"
    - "Chosen"
    - "Chowder"
    - "Chuck"
    - "Citizen Khan"
    - "The City and the City"
    - "Clarissa Explains it All"
    - "Class":
        set:
          tvdb_id: 309893
    - "Claws"
    - "Cleaning Up"
    - "Clerks: The Animated Series"
    - "Cleverman"
    - "The Climb"
    - "Clipped"
    - "Clique":
        set:
          tvdb_id: 324488
    - "Close to the Enemy":
        set:
          tvdb_id: 307831
    - "Club de Cuervos"
    - "Coast: New Zealand"
    - "Cobra Kai"
    - "Code Black":
        set:
          tvdb_id: 295780
    - "Code Monkeys"
    - "Code of a Killer"
    - "Cold Feet"
    - "Collateral"
    - "The Collection"
    - "Colony":
        set:
          tvdb_id: 284210
    - "Combat"
    - "Come Fly With Me"
    - "Comic Book Men"
    - "Community"
    - "Complete Savages"
    - "Con Man"
    - "Condor"
    - "Confess"
    - "The Conners"
    - "Containment":
        set:
          tvdb_id: 295767
    - "Continent 7: Antarctica"
    - "Continuum"
    - "Conviction"
    - "The Cool Kids"
    - "Cops"
    - "Corner Gas"
    - "Corporate"
    - "Cougar Town"
    - "Count Arthur Strong"
    - "Counterpart"
    - "Cousins For Life"
    - "Covert Affairs":
        set:
          tvdb_id: 104281
    - "Cow and Chicken"
    - "Crackanory"
    - "Crank Yankers"
    - "Crashing":
        alternate_name:
          - "Crashing (2016)"
          - "Crashing UK"
    - "Crashing (2017)":
        alternate_name:
          - "Crashing US"
        set:
          tvdb_id: 319153
    - "Crazy Ex-Girlfriend":
        set:
          tvdb_id: 295777
    - "Crazyhead":
        set:
          tvdb_id: 318000
    - "Creeped Out"
    - "Crikey its the Irwins"
    - "Criminal Minds":
        set:
          tvdb_id: 75710
    - "Criminal Minds: Beyond Borders":
        set:
          tvdb_id: 296654
    - "Crims"
    - "Crisis in Six Scenes":
        set:
          tvdb_id: 315314
    - "Crossbones"
    - "Crossing Lines"
    - "The Crossing"
    - "The Crow: Stairway to Heaven"
    - "The Crown":
        set:
          tvdb_id: 305574
    - "Crunch Time":
        set:
          tvdb_id: 315963
    - "Crusoe"
    - "The Cry"
    - "Cuckoo"
    - "The Cul de Sac"
    - "Cult"
    - "Curb Your Enthusiasm"
    - "Curious George"
    - "Cyberwar"
