series:
  television-list:
    - "Da Ali G Show"
    - "Da Jammies"
    - "Da Vincis Deamons"
    - "Dads"
    - "Dads Army"
    - "Dallas"
    - "Damages"
    - "Damien"
    - "Damnation"
    - "Dan Vs."
    - "Danger 5"
    - "The Dangerous Book for Boys"
    - "Dangerous Earth"
    - "Danis Castle"
    - "Daredevil"
    - "DARK"
    - "Dark Angel"
    - "Dark Heart"
    - "Dark Matter":
        set:
          tvdb_id: 292174
    - "Dark Matters: Twisted But True"
    - "Dark Net"
    - "Dark Shadows"
    - "Dark Side of the Sun":
        set:
          tvdb_id: 163161
    - "Darkness"
    - "Date My Dad"
    - "Dates"
    - "Davey and Goliath":
        set:
          tvdb_id: 71261
    - "David Attenborough's Conquest of the Skies"
    - "Dawn of the Croods"
    - "Day 5"
    - "Day Break"
    - "The Day of the Triffids (2009)"
    - "The Day the Universe Changed"
    - "Day Zero"
    - "Days of our Lives":
        set:
          tvdb_id: 70366
    - "Daytime Divas"
    - "De Dag"
    - "Dead Like Me"
    - "Dead Lucky"
    - "Dead of Summer"
    - "Deadbeat"
    - "Deadliest Catch":
        set:
          tvdb_id: 78957
    - "Deadly Class"
    - "Deadly Sins"
    - "Deadwood"
    - "Dear White People"
    - "Death Note"
    - "Deception"
    - "Decline and Fall":
        set:
          tvdb_id: 322122
    - "The Deep"
    - "Deep Space"
    - "Deep Space 69"
    - "Deep State"
    - "The Defenders (2010)":
        set:
          tvdb_id: 164521
    - "Defiance"
    - "The Defiant Ones"
    - "Degrassi: Next Class"
    - "The Deleted"
    - "Delicious"
    - "Delirium":
        alternate_name:
          - "Делириум"  # Russian
    - "Derry Girls"
    - "El Desconocido"
    - "Designated Survivor":
        set:
          tvdb_id: 311876
    - "Desperate Housewives"
    - "The Detail"
    - "The Detectives"
    - "Detectorists"
    - "The Detour"
    - "Detroiters"
    - "The Deuce"
    - "Deutschland 83"
    - "Dexter"
    - "Diablero"
    - "Diagnosis Murder"
    - "Dice"
    - "The Dick Van Dyke Show"
    - "Dietland"
    - "Difficult People"
    - "Diff'rent Strokes"
    - "Dig"
    - "Dilbert"
    - "Dimension 404"
    - "Dinosaurs"
    - "Dinotopia"
    - "Dirk Gently's Holistic Detective Agency"
    - "Dirty John"
    - "Dirty Sexy Money"
    - "A Discovery of Witches"
    - "Disenchantment"
    - "Disjointed"
    - "Divorce":
        set:
          tvdb_id: 314599
    - "Doc Martin"
    - "Doctor Doctor (2016)":
        alternate_name:
          - "Doctor Doctor AU"
    - "Doctor Foster"
    - "Doctor Who":
        alternate_name:
          - "Doctor Who (1963)"
        set:
          tvdb_id: 76107
    - "Doctor Who (2005)":
        set:
          tvdb_id: 78804
    - "Documentary Now"
    - "Dog the Bounty Hunter"
    - "Doggystyle"
    - "Dollhouse"
    - "Dominion"
    - "Don't Blame the Koalas"
    - "Don't Trust the B---- in Apartment 23":
        set:
          tvdb_id: 248812
    - "Dope"
    - "Dorothy and the Wizard of Oz"
    - "Double Dare"
    - "Doubt":
        set:
          tvdb_id: 311968
    - "Doug"
    - "Dow Hour of Great Mysteries"
    - "Downton Abbey":
        alternate_name:
          - "Аббатство Даунтон"  # Russian
        set:
          tvdb_id: 193131
    - "Downward Dog"
    - "Dr Katz Professional Therapist"
    - "Dr Ken"
    - "Dr Vegas"
    - "Dracula"
    - "Dragnet"
    - "Dragon Ball"
    - "Dragon Ball Super"
    - "Dragon Ball Z"
    - "The Dragon Prince"
    - "Dragons":
        alternate_name:
          - "Dragons: Defenders of Berk"
          - "Dreamworks Dragons"
    - "Drake and Josh"
    - "Drawn Together"
    - "Dream Corp LLC"
    - "The Drew Carey Show"
    - "The Drinky Crow Show"
    - "The Driver"
    - "Drop the Dead Donkey"
    - "Drunk History"
    - "Duck Dynasty"
    - "DuckTales"
    - "DuckTales (2017)"
    - "The Dukes of Hazzard"
    - "Dungeons and Dragons"
    - "The Durrells"
    - "Dynasties"
    - "Dynasty"
    - "Dystopia"

