series:
  television-list:
    - "Early Edition"
    - "Eastbound and Down"
    - "Eastsiders"
    - "Easy":
        set:
          tvdb_id: 314884
    - "Ed Edd n Eddy"
    - "The Ed Sullivan Show"
    - "Edha"
    - "Eerie Indiana"
    - "The Eighties"
    - "Elementary":
        set:
          tvdb_id: 255316
    - "Elizabeth I"
    - "Ellery Queen Mysteries"
    - "Elven"
    - "Emerald City":
        set:
          tvdb_id: 295779
    - "Empire (2015)":
        set:
          tvdb_id: 281617
    - "The End of the F***ing World"
    - "Endeavour"
    - "The Enfield Haunting"
    - "Entourage"
    - "Epicly Later'd"
    - "Episodes"
    - "The Equalizer"
    - "ER"
    - "Escape at Dannemora"
    - "Escape the Night"
    - "Eureka"
    - "Even Stevens"
    - "The Event"
    - "Everest Air"
    - "Everest Rescue"
    - "The Evermoor Chronicles"
    - "Everwood"
    - "Everybody Hates Chris"
    - "Everybody Loves Raymond"
    - "Everything Sucks"
    - "Evil Con Carne"
    - "Evil Touch"
    - "The Exorcist"
    - "The Expanse":
        set:
          tvdb_id: 280619
    - "Explorer"
    - "Extant"
    - "Extinct"
    - "Extrano Enemigo"
    - "Extreme Ghostbusters"
    - "Eye Candy"
    - "Eyewitness"
