###

series:
  television-list:
    - "F is for Family"
    - "F Troop"
    - "The Facts of Life"
    - "The Fades"
    - "Fairly Legal"
    - "The Fairly Oddparents"
    - "The Fall"
    - "Fallet"
    - "Falling Skies"
    - "Falling Water"
    - "False Flag"
    - "Fam"
    - "Family Guy":
        set:
          tvdb_id: 75978
    - "The Family Law"
    - "Family Matters"
    - "Family Ties"
    - "Family Time"
    - "Famous in Love"
    - "Farang"
    - "Fargo":
        set:
          tvdb_id: 269613
    - "Farscape"
    - "Fat Actress"
    - "Father Brown"
    - "FBI"
    - "Fear Itself"
    - "Fear the Walking Dead"
    - "Fearless"
    - "Femme Fatales"
    - "La Femme Nikita"
    - "FEUD":
        set:
          tvdb_id: 322466
    - "Field of Blood"
    - "Fillmore"
    - "Filty Preppy Teens"
    - "Filty Rich"
    - "Final Space"
    - "Finding Carter"
    - "Finding Joy"
    - "Firefly"
    - "The First"
    - "The Five UK"
    - "Five Came Back"
    - "Fix Her Up"
    - "Fixer Upper"
    - "Flaked"
    - "The Flash (2014)":
        set:
          tvdb_id: 279121
    - "Flash Gordon (1996)"
    - "Flash Gordon (2008)"
    - "Fleabag"
    - "Flesh and Bone"
    - "Flight of the Conchords"
    - "Flikken Maastricht"
    - "The Flintstones"
    - "Flodder"
    - "Fluffy's Food Adventures"
    - "The Following"
    - "Fonejacker"
    - "For the People"
    - "The Forest"
    - "Forever"
    - "Forgotten Girls"
    - "Formula1"
    - "Fortitude"
    - "The Fosters"
    - "Four in the Morning"
    - "Fractured Flickers"
    - "Fraggle Rock"
    - "The Frankenstein Chronicles"
    - "Frankenstein Family"
    - "Frankie Boyles New World Order"
    - "Frankie Drake Mysteries"
    - "Fraiser"
    - "Freekazoid"
    - "Freakish"
    - "Freaks and Geeks"
    - "Freddy's Nightmare"
    - "Free Rein"
    - "Frequency":
        set:
          tvdb_id: 311958
    - "Fresh Meat"
    - "Fresh Off the Boat":
        set:
          tvdb_id: 281618
    - "The Fresh Prince of Bel Air"
    - "Friday Night Dinner"
    - "Friday Night Lights"
    - "Friday the 13th: The Series"
    - "Friends"
    - "Friends from College"
    - "Friends with Benefits"
    - "Fringe"
    - "From Dusk Till Dawn: The Series"
    - "Frontier (2016)"
    - "Fugitiva"
    - "Full Circle"
    - "Full House"
    - "Fuller House"
    - "Futurama"
    - "Future Man"

