###

series:
  television-list:
    - "F Troop"
    - "Falling Skies"
    - "False Flag"
    - "Family Guy":
        set:
          tvdb_id: 75978
    - "Famous in Love"
    - "Fargo":
        set:
          tvdb_id: 269613
    - "Fear the Walking Dead"
    - "Fearless"
    - "FEUD":
        set:
          tvdb_id: 322466
    - "Fillmore"
    - "Filty Rich"
    - "Final Space"
    - "Fixer Upper"
    - "The Flash (2014)":
        set:
          tvdb_id: 279121
    - "Fluffy's Food Adventures"
    - "For the People"
    - "The Fosters"
    - "The Frankenstein Chronicles"
    - "Freakish"
    - "Frequency":
        set:
          tvdb_id: 311958
    - "Fresh Off the Boat":
        set:
          tvdb_id: 281618
    - "Friends"
    - "Fringe"
    - "From Dusk Till Dawn: The Series"
    - "Frontier (2016)"
    - "Fuller House"
    - "Futurama"
    - "Future Man"
