###

series:
  television-list:
    - "Halfworlds"
    - "Halt and Catch Fire":
        set:
          tvdb_id: 271910
    - "Hamilton's Pharmacopeia"
    - "Hammer House of Mystery and Suspense"
    - "Hand of God"
    - "The Handmaids Tale"
    - "Hang Ups"
    - "Hannah Montana"
    - "Hannibal"
    - "Hap and Leonard":
        set:
          tvdb_id: 305687
    - "Happy"
    - "Happy Together"
    - "Happy Town"
    - "Hard Sun"
    - "The Hard Times of RJ Berger"
    - "Harley and the Davidsons"
    - "Harlots"
    - "HarmonQuest"
    - "Harpers Island"
    - "Harrow"
    - "Harvey Beaks"
    - "Harvey Birdman Attorney at Law"
    - "Haters Back Off"
    - "Hatfields and McCoys"
    - "The Haunting of Hill House"
    - "Have I Got News for You"
    - "Haven"
    - "Hawaii Five-0 (2010)":
        set:
          tvdb_id: 164541
    - "He-Man and the Masters of the Universe"
    - "Head 2 Head"
    - "Head of the Class"
    - "Hear No Evil"
    - "The Heart, She Holler"
    - "Heartbeat"
    - "Heartland"
    - "Heathers"
    - "Helix"
    - "Hell on Wheels"
    - "Hello Cheeky"
    - "Henry Danger"
    - "Hercules"
    - "Here and Now"
    - "Heros"
    - "Heros Reborn"
    - "High Maintenance"
    - "Highlander"
    - "Highlander: The Animated Series"
    - "Highlander: The Raven"
    - "Highway Patrol"
    - "Highway to Heaven"
    - "HIM"
    - "Hinterland"
    - "Hit the Road"
    - "The Hitchhiker"
    - "The Hitchhiker's Guide to the Galaxy"
    - "Hold the Sunset"
    - "Holliston"
    - "The Hollow Crown"
    - "The Holltwood Puppet Shitshow"
    - "Home from Home"
    - "Home Improvement"
    - "Home Movies"
    - "Homeland":
        set:
          tvdb_id: 247897
    - "Honeymooners"
    - "The Honourable Woman"
    - "The Hook Up Plan"
    - "Hooten and the Lady"
    - "Hope and Faith"
    - "Hornblower"
    - "Hospital People"
    - "Hot Streets"
    - "The Hotel Barclay"
    - "Hotel Beau Sejor"
    - "Hotel of Mum and Dad"
    - "Houdini"
    - "Houdini and Doyle"
    - "House"
    - "House of Anubis"
    - "House of Cards"
    - "House of Lies"
    - "House of Mouse"
    - "How I Met Your Mother"
    - "How It's Made"
    - "How the Universe Works"
    - "How to Get Away with Murder":
        alternate_name:
          - "Как избежать наказания за убийство"  # Russian
    - "Howards End"
    - "Huangs World"
    - "The Huckleberry Hound Show"
    - "Human Target"
    - "Human Universe"
    - "Humans":
        set:
          tvdb_id: 292124
    - "Hunderby"
    - "The Hunt"
    - "Hunter"
