###

series:
  television-list:
    - "Halt and Catch Fire":
        set:
          tvdb_id: 271910
    - "Hap and Leonard":
        set:
          tvdb_id: 305687
    - "Hawaii Five-0 (2010)":
        set:
          tvdb_id: 164541
    - "Home from Home"
    - "Homeland":
        set:
          tvdb_id: 247897
    - "How to Get Away with Murder":
        alternate_name:
          - "Как избежать наказания за убийство"  # Russian
    - "Humans":
        set:
          tvdb_id: 292124
    - "Hunderby"