series:
  television-list:
    - "I Am Frankie"
    - "I Am Weasel"
    - "I Dream of Jeannie"
    - "I Feel Bad"
    - "I Love Dick"
    - "I Love Lucy"
    - "I Love You America":
        alternate_name:
          "I Love You America with Sarah Silverman"
    - "I Shouldn't Be Alive"
    - "iCarly"
    - "Ice"
    - "Idiotsitter"
    - "Ill Behaviour"
    - "I'm Dying Up Here"
    - "I'm Sorry"
    - "Imaginary Mary"
    - "The Immortal"
    - "Impastor"
    - "Impossible Engineering"
    - "Imposters":
        set:
          tvdb_id: 320520
    - "Impulse"
    - "In Living Color"
    - "In the Dark"
    - "In the Flesh"
    - "In Treatment"
    - "The Inbetweeners"
    - "Incorporated":
        set:
          tvdb_id: 315177
    - "The Incredible Hulk"
    - "Informer"
    - "Ingobernable"
    - "Inhumans"
    - "Inquistion"
    - "Insecure"
    - "Inside Balmoral"
    - "Insomnia"
    - "Inspector Gadget"
    - "Inspector George Gently"
    - "Instinct"
    - "Intelligence (2014)":
        alternate_name:
          - "Intelligence US"
    - "Into the Badlands":
        set:
          tvdb_id: 289079
    - "Into the Dark"
    - "Intruders"
    - "Invader Zim"
    - "The Inbetweeners"
    - "The Incredible Hulk"
    - "The Innocents"
    - "The Invisible Man"
    - "Iron Fist"
    - "IT"
    - "The IT Crowd"
    - "It's Always Sunny in Philadelphia"
    - "iZombie"
