series:
  television-list:
    - "Jack and Bobby"
    - "Jack Irish"
    - "Jackass"
    - "Jackie Chan Adventures"
    - "Jacqueline and Jilly"
    - "JAG"
    - "James May: The Reassembler"
    - "James Mays Man Lab"
    - "Jamestown"
    - "The Jamie Foxx Show"
    - "Jamies Quick and Easy Food"
    - "Jane the Virign"
    - "Janet King"
    - "Jay Leno's Garage (2015)":
        set:
          tvdb_id: 301592
    - "Jean-Claude Van Johnson"
    - "The Jeffersons"
    - "Jekyll and Hyde"
    - "The Jellies"
    - "Jeremiah"
    - "Jericho"
    - "Jericho (2016)"
    - "Jessie"
    - "The Jetsons"
    - "Joan of Arcadia"
    - "John Adams"
    - "John Doe"
    - "Johnny Bravo"
    - "Johnny Test"
    - "Jon Benjamin has a Van"
    - "Jon Glaser Loves Gear"
    - "Jonathan Strange and Mr. Norrell"
    - "Jonny Quest"
    - "Josh"
    - "Journeyman"
    - "Julkalendern"
    - "Justice"
    - "Justice League Action"
    - "Justified"
