###

series:
  television-list:
    - "The L Word"
    - "LA to Vegas"
    - "Lady Dynamite"
    - "Laid"
    - "The Larry Sanders Show"
    - "Las Vegas"
    - "Last Chance High"
    - "The Last Kingdom"
    - "The Last Man On Earth"
    - "Last Man Standing":
        set:
          tvdb_id: 248834
    - "The Last O.G."
    - "The Last Panthers"
    - "The Last Post"
    - "Last Resort"
    - "The Last Ship"
    - "The Last Tycoon":
        set:
          tvdb_id: 315364
    - "Laverne and Shirley"
    - "Law and Order: SVU":
        alternate_name:
          - "Law and Order Special Victims Unit"
        set:
          tvdb_id: 75692
    - "Law and Order: True Crime"
    - "The League"
    - "The League of Gentlemen"
    - "The Leftovers"
    - "Legacies"
    - "The Legend of Korra"
    - "The Legend of Master Legend"
    - "Legend of the Seeker"
    - "The Legend of Zelda"
    - "Legends"
    - "Legends of the Hidden Temple"
    - "Legends of the Lost with Megan Fox"
    - "Legends of Tomorrow":
        alternate_name:
          - "DC's Legends of Tomorrow"
        set:
          tvdb_id: 295760
    - "Legion":
        set:
          tvdb_id: 320724
    - "Legit"
    - "Leonardo"
    - "Less than Perfect"
    - "The Lesson"
    - "Lethal Weapon":
        set:
          tvdb_id: 311790
    - "Let's Get Physical"
    - "Letterkenny"
    - "The Level"
    - "Leverage"
    - "Lewis"
    - "Liar"
    - "Liberty Crossing"
    - "The Librarians (2014)":
        alternate_name:
          - "Библиотекари /The Librarians"  # Russian
        set:
          tvdb_id: 281709
    - "Life in Pieces":
        set:
          tvdb_id: 295778
    - "Life on Mars":
        alternate_name:
          - "Life on Mars UK"
          - "Life on Mars (2006)"
    - "Life on Mars (2008)":
        alternate_name:
          - "Life on Mars US"
    - "Life Sentence"
    - "Lifeline"
    - "Light as a Feather"
    - "Lights Out"
    - "Lilo and Stitch: The Series"
    - "Lilyhammer"
    - "Limitless"
    - "Lindsay Lohan's Beach Club"
    - "Line of Duty"
    - "Lion Kingdom"
    - "The Lion Guard"
    - "Little Dog"
    - "The Little Drummer Girl"
    - "Little Lunch"
    - "The Little Mermaid"
    - "Little Things"
    - "Little Women (2017)"
    - "Living Biblically"
    - "The Lizzie Borden Chronicles"
    - "Lloyd in Space"
    - "Loaded (2017)"
    - "The Loch"
    - "Lock n Load with R Lee Ermey"
    - "Locked Up"
    - "Lodge 49"
    - "Lois and Clark"
    - "London Spy"
    - "The Lone Gunmen"
    - "The Long Road Home"
    - "Long Strange Trip"
    - "Longmire"
    - "The Looming Tower"
    - "Lopez":
        set:
          tvdb_id: 308734
    - "Lore"
    - "Lost Girl"
    - "Lost in Space"
    - "Lost in Space (2018)"
    - "Loudermilk"
    - "Louie"
    - "Love"
    - "Love Blows"
    - "Love Child"
    - "Love Nina"
    - "Love Your Garden"
    - "Lovesick"
    - "Lucifer":
        set:
          tvdb_id: 295685
    - "The Lucy Show"
    - "Luis Miguel the Series"
