###

series:
  television-list:
    - "MacGyver":
        set:
          tvdb_id: 77847
    - "MacGyver (2016)":
        set:
          tvdb_id: 311902
    - "Mad Men":
        set:
          tvdb_id: 80337
    - "Madam Secretary"
    - "MADtv"
      #regexp: "^madtv?"
    - "The Man in the High Castle":
        set:
          tvdb_id: 295829
    - "Making History (2017)":
        set:
          tvdb_id: 311833
    - "Major Crimes"
    - "Malcolm in the Middle"
    - "Mammon"
    - "Man Down"
    - "Man Seeking Woman"
    - "Man With a Plan"
    - "Marlon"
    - "Mary Kills People"
    - "The Magicians"
    - "The Marvelous Mrs. Maisel"
    - "Marvels Agents of S H I E L D"
    - "Masters of Sex"
    - "The Mayor"
    - "McMafia"
    - "Me, Myself & I":
        alternate_name: "Me, Myself and I"
    - "MECH-X4"
    - "Metalocalypse"
    - "Metropolis"
    - "Miami Vice"
    - "The Mick"
    - "The Middle"
    - "Midnight, Texas"
    - "Mighty Max"
    - "Mike Judge Presents Tales From the Tour Bus"
    - "Mike Tyson Mysteries"
    - "Mindhunter"
    - "The Mindy Project"
    - "Misfit Garage"
    - "The Missing"
    - "The Mist"
    - "Modern Family"
    - "Mom"
    - "Monk"
    - "Monster (2017)"
    - "Mosiac"
    - "Motherland"
    - "A Mothers Son"
    - "Mountain: Life at the Extreme"
    - "Mr. D"
    - "Mr. Mercedes"
    - "Mr. Pickles"
    - "Mr. Robot"
    - "Murdoch Mysteries"
    - "My Wife and Kids"
    - "Mystery Science Theater 3000"
    - "Mystery Science Theater 3000: The Return"
    - "Mysticons"
