###

series:
  television-list:
    - "M.I. High"
    - "MacGyver":
        set:
          tvdb_id: 77847
    - "MacGyver (2016)":
        set:
          tvdb_id: 311902
    - "Mad Dogs"
    - "Mad Men":
        set:
          tvdb_id: 80337
    - "Madam Secretary"
    - "MADtv"
      #regexp: "^madtv?"
    - "Madventures"
    - "The Magic School Bus Rides Again"
    - "The Magicians (2015)"
    - "The Magilla Gorilla Show"
    - "Magnum PI"
    - "Maigret (2016)"
    - "Major Crimes"
    - "Making History (2017)":
        set:
          tvdb_id: 311833
    - "Malcolm in the Middle"
    - "Mammon"
    - "Man Down"
    - "The Man From Uncle"
    - "Man in an Orange Shirt"
    - "The Man in the High Castle":
        set:
          tvdb_id: 295829
    - "Man Seeking Woman"
    - "The Man Show"
    - "Man vs Wild"
    - "Man With a Plan"
    - "Maniac"
    - "Manifest"
    - "Le Mans: Racing is Everything"
    - "Marcella"
    - "El Marginal"
    - "Marlon"
    - "Married with Children"
    - "Mars (2016)"
    - "Mars: The Secret Science"
    - "Marseille"
    - "Martha and Snoop's Potluck Dinner Party"
    - "The Marvelous Mrs. Maisel"
    - "Mary Kills People"
    - "Mary-Jane (2016)"
    - "Mash"
    - "Masters of Horror"
    - "Masters of Sex"
    - "Matilda and the Ramsay Bunch"
    - "Max Headroom"
    - "The Maxx"
    - "Mayans M.C."
    - "The Mayor"
    - "McHales Navy"
    - "McMafia"
    - "Me Chuma de Bruna"
    - "Me, Myself & I":
        alternate_name: "Me, Myself and I"
    - "MECH-X4"
    - "Medical Investigation"
    - "Medici the Magnificent"
    - "Meerkat Manor"
    - "Melissa and Joey"
    - "The Men Who Built America"
    - "Merlin"
    - "Metal Hurlant Chronicles"
    - "Metalocalypse"
    - "Metropolis"
    - "Miami Vice"
    - "The Michael J Fox Show"
    - "The Mick"
    - "Micky Mouse (2013)"
    - "The Middle"
    - "Midnight Sun"
    - "Midnight, Texas"
    - "The Mighty Boosh"
    - "Mighty Max"
    - "Mike Judge Presents Tales From the Tour Bus"
    - "Mike, Lu, and Og"
    - "Mike Tyson Mysteries"
    - "Millennium (1996)"
    - "A Million Little Things"
    - "Milo Murphys Law"
    - "Mind Field"
    - "Minder"
    - "Mindhunter"
    - "The Mindy Project"
    - "Miraculous Tales of Ladybug and Cat Noir"
    - "Mirzapur"
    - "Les Miserables"
    - "Misfit Garage"
    - "Misfits"
    - "Miss Fisher's Murder Mysteries"
    - "Miss Guided"
    - "Miss Sherlock"
    - "The Missing"
    - "Mission Impossible"
    - "Missions"
    - "The Mist"
    - "Mister Rogers Neighborhood"
    - "Mobile Suit Gundam Wing"
    - "Modern Family"
    - "Modern Marvels"
    - "Modus"
    - "Mom"
    - "Momo Salon"
    - "Monk"
    - "Monkey Thieves"
    - "Monkman and Seagulls Genius Guide to Britain"
    - "Monster (2017)"
    - "Monsters"
    - "Monty Pythons Flying Circus"
    - "Moon Machines"
    - "Moonbase"
    - "Moonbeam City"
    - "Moone Boy"
    - "Moonlight"
    - "Moonlighting"
    - "Moral Orel"
    - "Mork and Mindy"
    - "Mosiac"
    - "Motherboard"
    - "Motherland"
    - "A Mothers Son"
    - "Mountain: Life at the Extreme"
    - "Mr. Bean: The Animated Series"
    - "Mr. and Mrs. Murder"
    - "Mr. D"
    - "Mr. Ed"
    - "Mr. Inbetween"
    - "Mr. Mercedes"
    - "Mr. Pickles"
    - "Mr. Robot"
    - "Mr. Sunshine"
    - "Mrs. Brown's Boys"
    - "Mrs. Wilson"
    - "Ms Incorporated"
    - "The Munsters"
    - "The Muppet Show"
    - "Murder in the First"
    - "Murdoch Mysteries"
    - "Murphy Brown"
    - "Music City"
    - "The Musketeers"
    - "Mutiny"
    - "My Brilliant Friend"
    - "My Favorite Martian"
    - "My Life as a Teenage Robot"
    - "My Little Pony"
    - "My Mad Fat Diary"
    - "My Mother and Other Strangers"
    - "My Name is Earl"
    - "My Secret Sex Fantasy"
    - "My Wife and Kids"
    - "Mystery Road"
    - "Mystery Science Theater 3000"
    - "Mystery Science Theater 3000: The Return"
    - "Mysticons"
    - "Mythbusters"
    - "Mythbusters: The Search"

