###

series:
  television-list:
    - "Naked News"  # FIXME: need regexp
    - "Naked SNCTM"
    - "Narcos"
    - "Nashville (2012)"
    - "Natural World"
    - 'Nazi Megastructures'
    - "No Ordinary Family"
    - "NCIS"
    - "NCIS: New Orleans":
        alternate_name:
          - "Морская полиция: Новый Орлеан"  # Russian
    - "New Girl"
    - "Newtons Law"
    - "The Night Shift"
    - "No Tomorrow"
    - "Nobility"
    - "North and South"
    - "NOVA"
    - "Nowhere Boys"
    - "Numb3rs"
