###

series:
  television-list:
    - "Nailed It"
    - "Naked News"  # FIXME: need regexp
    - "Naked SNCTM"
    - "The Nanny"
    - "Napoleon Dynamite"
    - "Narcos"
    - "Narcos Mexico"
    - "Nasas Unexplaied Files"
    - "Nascar Camping World Truck Series"
    - "Nascar Monster Energy Cup Series"
    - "Nascar Xfinity Series"
    - "Nashville (2012)"
    - "Nathan for You"
    - "National Parks Top 10"
    - "Native America"
    - "Natural World"
    - "Nature"
    - "Nazi Megastructures"
    - "Next of Kin"
    - "No Ordinary Family"
    - "NCIS"
    - "NCIS: Los Angeles"
    - "NCIS: New Orleans":
        alternate_name:
          - "Морская полиция: Новый Орлеан"  # Russian
    - "Ned and Stacy"
    - "Neds Declassified School Survival Guide"
    - "The Neighborhood"
    - "Neo Yokio"
    - "Neon Joe Werewolf Hunter"
    - "Neverwhere"
    - "New Amsterdam"
    - "The New Adventures of Gilligan"
    - "The New Adventures of Winnie the Pooh"
    - "The New Batman Adventures"
    - "The New Legends of Monkey"
    - "The New Scooby-doo Movies"
    - "The New Vips"
    - "The Newsroom"
    - "New Girl"
    - "New Worlds"
    - "Newtons Law"
    - "Next of Kin"
    - "Night Court"
    - "Night Gallery"
    - "The Night Manager"
    - "The Night Of"
    - "The Night Shift"
    - "Nightcap"
    - "Nightflyers"
    - "Nightmare Worlds of HG Wells"
    - "Niko and the Sword of Light"
    - "The Nineties"
    - "Nip Tuck"
    - "Nitro Circus Live"
    - "No Activity"
    - "No Easy Days"
    - "No Limit"
    - "No Offense"
    - "No Ordinary Family"
    - "No Second Chance"
    - "No Tomorrow"
    - "Nobility"
    - "Nobodies"
    - "Noel Fielding's Luxury Comedy"
    - "The Normans"
    - "Norsemen"
    - "Norske Rednecks"
    - "North America"
    - "North and South"
    - "Northern Exposure"
    - "Not Going Out"
    - "Not Safe for Work"
    - "NOVA"
    - "Nowhere"
    - "Nowhere Boys"
    - "Numb3rs"
    - "Nymphs"

