###

series:
  television-list:
    - "The OA"
    - "Oasis"
    - "Odd Mom Out"
    - "Once Upon a Time"
    - "One Mississippi"
    - "The Originals"
    - "Orphan Black"
    - "The Orville"
    - "Outlander"
    - "Outlanders"
    - "Outsiders"
