###

series:
  television-list:
    - "The OA"
    - "Oasis"
    - "Odd Mom Out"
    - "Once Upon a Time"
    - "One Mississippi"
    - "One Strange Rock"
    - "Only Fools and Horses"
    - "Open Heart"
    - "The Originals"
    - "Orphan Black"
    - "The Orville"
    - "Outcast"
    - "Outlander"
    - "Outlanders"
    - "Outsiders"
    - "Over the Garden Wall"
