###

series:
  television-list:
    - "The Path"
    - "Patriot"
    - "Paw Patrol"
    - "Peaky Blinders"
    - "Pelswick"
    - "Penny Dreadful"
    - "People of Earth"
    - "Pepper Ann"
    - "Philip K. Dick's Electric Dreams"
    - "A Place To Call Home"
    - "The Planets"
    - "Porters"
    - "Porridge (2017)"
    - "Power"
    - "Power Rangers"
    - "Powerless"
    - "The Powerpuff Girls (2016)"
    - "Preacher"
    - "The Pretender"
    - "Pretty Little Liars"
    - "Prime Suspect 1973"
    - "Primeval"
    - "Profugos"
    - "Pulse":
        alternate_name:
          - "Pulse AU"
    - "The Punisher":
        alternate_name:
          - "Marvels The Punisher"
    - "Pure"
