###

series:
  television-list:
    - "The Path"
    - "Patriot"
    - "Paw Patrol"
    - "Pelswick"
    - "Penny Dreadful"
    - "People of Earth"
    - "Pepper Ann"
    - "The Planets"
    - "Power"
    - "Power Rangers"
    - "Powerless"
    - "The Powerpuff Girls (2016)"
    - "Preacher"
    - "The Pretender"
    - "Pretty Little Liars"
    - "Prime Suspect 1973"
    - "Pulse":
        alternate_name:
          - "Pulse AU"
    - "Pure"
