###

series:
  television-list:
    - "Pacific Heat"
    - "Pakt"
    - "Pan Am"
    - "Paradise PD"
    - "Parenting for Idiots"
    - "Parks and Recreation"
    - "Partners"
    - "Party Down"
    - "Party Legends"
    - "Party of Five"
    - "The Path"
    - "Patrick Melrose"
    - "Patriot"
    - "Paula"
    - "Paw Patrol"
    - "The Pacific"
    - "The Partridge Family"
    - "The Passage"
    - "The Passenger"
    - "The Passing Bells"
    - "The Path"
    - "The Paynes"
    - "Peabody and Sherman"
    - "Peaky Blinders"
    - "Pee Wee's Playhouse"
    - "Peep Show"
    - "Pelswick"
    - "Pen and Teller Bullshit"
    - "Penny Dreadful"
    - "Penoza"
    - "People Just Do Nothing"
    - "People of Earth"
    - "Pepper Ann"
    - "Person of Interest"
    - "Persons Unknown"
    - "Pete the Cat"
    - "Petticoat Junction"
    - "Phil of the Future"
    - "Philip K. Dick's Electric Dreams"
    - "Phineas and Ferb"
    - "Picket Fences"
    - "Picnic at Hanging Rock"
    - "Pine Gap"
    - "Pingu"
    - "The Pink Panther"
    - "The Pinkertons"
    - "Pinky and the Brain"
    - "Pinky, Elmyra and the Brain"
    - "The Pizza Show"
    - "A Place To Call Home"
    - "The Planets"
    - "Playing House"
    - "Please Like Me"
    - "Pls Like"
    - "Pluton Brb Nero"
    - "Pod Prikritie"
    - "Poldark"
    - "Police Squad"
    - "Porridge (2017)"
    - "Porters"
    - "Portlandia"
    - "Pose"
    - "Power"
    - "Power Rangers":
          alternate_name:
            - "Mighty Morphin Power Rangers"
            - "Power Rangers Dino Super Charge"
            - "Power Rangers Dino Thunder"
            - "Power Rangers Megaforce"
            - "Power Rangers Ninja Steel"
            - "Power Rangers Ninja Storm"
            - "Power Rangers Operation Overdrive"
            - "Power Rangers RPM"
            - "Power Rangers Wild Force"
    - "Powerless"
    - "Powers (2015)"
    - "The Powerpuff Girls (2016)"
    - "Pramface"
    - "Preacher"
    - "The Pretender"
    - "Pretty Little Liars"
    - "Prime Suspect 1973"
    - "Primeval"
    - "Prison Break"
    - "Prisoners of War"
    - "Private Eyes"
    - "Private Practice"
    - "Profugos"
    - "Project Blue Book"
    - "Project Grizzly"
    - "The Promise"
    - "Psiconautas"
    - "Puberty Blues"
    - "Puffin Rock"
    - "Pulse":
        alternate_name:
          - "Pulse AU"
          - "Pulse (2017)"
    - "Punch Man"
    - "Punkd"
    - "The Punisher":
        alternate_name:
          - "Marvels The Punisher"
    - "A Pup Named Scooby-Doo"
    - "Pure"
    - "The Purge"
    - "Puse Genius"
    - "Pushing Daisies"

