###

series:
  television-list:
    - "The Ranch"
    - "Ransom"
    - "Ravens Home"
    - "Ray Donovan"
    - "Rebel"
    - "Red Oaks"
    - "Reign"
    - "Regular Show"
    - "The Returned":  # 2012
        alternate_name:
          - "Les Revanants"
    - "Rick and Morty"
    - "Ringer"
    - "Riverdale"
    - "Road Hauks"
    - "Robot Chicken"
    - "Rogue"
    - "Room 104"
    - "Rosewood"
    - "The Royals"
    - "Rugrats"
