###

series:
  television-list:
    # A
    - "Railroad Australia"
    - "The Rain"
    - "Rake"
    - "The Ranch"
    - "Ransom"
    - "Rapture"
    - "Ravens Home"
    - "Ravenswood"
    - "Rawhide"
    - "The Ray Bradbury Theater"
    - "Ray Donovan"
    # E
    - "Reading Rainbow"
    - "The Real Adventures of Jonny Quest"
    - "Real Rob"
    - "The Real Ghostbusters"
    - "The Real Oneals"
    - "Reaper"
    - "The Reaping"
    - "Reba"
    - "Rebel"
    - "Rebellion"
    - "Recess"
    - "Red Band Society"
    - "Red Dwarf"
    - "Red Oaks"
    - "The Red Road"
    - "The Red Tent"
    - "Red Widow"
    - "Redrum"
    - "The Refugees"
    - "Regular Show"
    - "Reign"
    - "Rel"
    - "Rellik"
    - "The Ren and Stimpy Show"
    - "Rena Rama Rolf"
    - "Renford Rejects"
    - "Reno 911"
    - "Republic of Doyle"
    - "Requiem"
    - "Rescue Me"
    - "The Resident"
    - "Residue"
    - "Resistance"
    - "Resurrection"
    - "The Returned":  # 2012
        alternate_name:
          - "Les Revanants"
    - "The Returned (2015)"
    - "Reverie"
    - "Revolution"
    # I
    - "Richard Hammonds Crash Course"
    - "Richard Hammonds Engineering Connections"
    - "The Riches"
    - "Richie Rich"
    - "Rick and Morty"
    - "Ride Upon the Storm"
    - "Ride with Norman Reedus"
    - "Ringer"
    - "Ripper Street"
    - "Rise"
    - "Ritual"
    - "River"
    - "The River"
    - "Riverdale"
    - "Riviera"
    - "Rizzoli and Isles"
    # O
    - "Road Hauks"
    - "Roadies"
    - "Rob and Big"
    - "Robocop"
    - "Robot Chicken"
    - "Robotboy"
    - "Rock the Park"
    - "Rocket Power"
    - "The Rockford Files"
    - "Rockos Modern Life"
    - "Rogue"
    - "Roman Empire Reign of Blood"
    - "The Romanoffs"
    - "Rome"
    - "Romper Stomper"
    - "The Rookie"
    - "Room 104"
    - "Roomates"
    - "Roots"
    - "Rose Red"
    - "Roseanne"
    - "Rosewood"
    - "Rostered On"
    - "Roswell"
    - "Roswell New Mexico"
    - "Roughnecks: The Starship Troopers Chronicles"
    - "Round the Twist"
    - "Royal Institution Christmas Lectures"
    - "The Royals"
    # U
    - "The Rubberbandits Guide to Everything"
    - "Rubicon"
    - "Rugrats"
    - "Runaway"
    - "Runaways":
        alternate_name:
          - "Marvels Runaways"
    - "Rush Hour"
    # W
    - "RWBY"

