###

series:
  television-list:
    - "The Ranch"
    - "Ransom"
    - "Rapture"
    - "Ravens Home"
    - "Ray Donovan"
    - "Real Rob"
    - "Rebel"
    - "Recess"
    - "Red Oaks"
    - "Reign"
    - "Regular Show"
    - "Rellik"
    - "Republic of Doyal"
    - "The Resident"
    - "The Returned":  # 2012
        alternate_name:
          - "Les Revanants"
    - "Reverie"
    - "Rick and Morty"
    - "Ringer"
    - "Rise"
    - "Ritual"
    - "Riverdale"
    - "Road Hauks"
    - "Robot Chicken"
    - "Rogue"
    - "Room 104"
    - "Roseanne"
    - "Rosewood"
    - "The Royals"
    - "Rugrats"
    - "Runaways":
        alternate_name:
          - "Marvels Runaways"
