###

series:
  television-list:
    # A
    - "The Saboteurs"
    - "Sabrina: The Teenage Witch"
    - "Safe"
    - "Safe Harbour"
    - "Safe House"
    - "Salem"
    - "Sally4ever"
    - "Salvation"
    - "Sam and Cat"
    - "Samurai Jack"  # 2001
    - "Santa Clarita Diet"
    - "The Sarah Connor Chronicles"
    - "The Sarah Jane Adventures"
    - "The Sarah Silverman Program"
    - "Saved by the Bell"
    - "Saved by the Bell: The College Years"
    - "Saving Hope"
    - "Saving Lives at Sea"
    # C
    - "Scandal (2012)":
        alternate_name: Scandal US  # ???
    - "Schitts Creek"
    - "School Inc"
    - "Schooled"
    - "Scooby-Doo and Scappy-Doo":
        alternate_name:
          - "Scooby-Doo & Scappy-Doo"
    - "Scooby-Doo Mystery Incorporated"
    - "The Scooby-Doo Show"  # 1976
    - "Scooby-Doo Where Are You"
    - "Scorpion":
        alternate_name:
          - "Скорпион"
    - "Scott and Bailey"
    - "Scream"
    - "Scream Queens"
    - "Scrubs"
    # E
    - "Sea Oak"
    - "Sea Patrol"
    - "SEAL Team"
    - "Sealab"
    - "Seaquest"
    - "The Search for a New Earth"
    - "Search Party"
    - "Second Chance"
    - "Second Jen"
    - "The Secret Adventures of Jules Verne"
    - "Secret City"
    - "The Secret Daughter"
    - "Secret Diary of a Call Girl"
    - "The Secret Life of the American Teenager"
    - "Secret State"
    - "Secrets of the Underground"
    - "Secrets of the Zoo"
    - "Seinfeld"
    - "The Selection: Special Operations Experiment"
    - "Selfie"
    - "Sense8"
    - "A Series of Unfortunate Events"
    - "Sesame Street"
    - "Seven Types of Ambiguity"
    - "The Seventies"
    - "Sex and Drugs and Rock and Roll"
    - "Sex and the City"
    - "Sex Education"
    - "Sez Les"
    # H
    - "Shades of Blue"
    - "Shadowhunters"
    - "Shaggy and Scobby-Doo Get a Clue"
    - "Shakespeare and Hathaway Private Investigators"
    - "Shameless"
    - "The Shannara Chronicles"
    - "Shark Week"
    - "Sharp Objects"
    - "Sharpe"
    - "Shattered"
    - "She-ra Princess of Power"
    - "Sherlock"
    - "Sherlock Holmes"
    - "Shetland"
    - "The Shield"
    - "Shinesty"
    - "The Shivering Truth"
    - "Shooter"
    - "Shots Fired"
    - "Shrink"
    - "Shut Eye"
    # I
    - "Siberia"
    - "Sick Note"
    - "Significant Mother"
    - "The Silence"
    - "Silicon Valley"
    - "Silk"
    - "Silver Spoons"
    - "The Simpsons"
    - "Single Parents"
    - "The Sinner"
    - "Siren"
    - "Sisters"
    - "Six"
    - "Six Feet Under"
    - "The Sixties"
    # K
    - "Skam"
    - "Skin to the Max"
    - "The Skinny Dip"
    - "Skins"
    - "Skit Happens"
    - "Skylander Academy"
    - "Skyward"
    # L
    - "Slasher"
    - "Sleeper Cell"
    - "Sleepy Hollow"
    - "Slugterra"
    - "Slutever"
    # M
    - "Smart Guy"
    - "Smileys People"
    - "SMILF"
    # N
    - "Snatch"
    - "Sneaky Pete"
    - "The Sniffer"
    - "Snowfall"
    # O
    - "Some Girls"
    - "Somewhere Between"
    - "The Son"
    - "Son of the Beach"
    - "Sons of Anarchy"
    - "Sons of Tucson"
    - "The Sopranos"
    - "Sorry for Your Loss"
    - "South of Hell"
    - "South Park"
    - "South Riding"
    # P
    - "Space: Above and Beyond"
    - "Space Ghost: Coast to Coast"
    - "Spaced"
    - "Space's Deepest Secrets"
    - "Sparticus"
    - "Spawn"
    - "Speechless"
    - "Speed is the New Black"
    - "Speed Racer"
    - "Spider-Man":
        alternate_name:
          - "Marvel's Spider-Man"
    - "Spin"
    - "Spin City"
    - "Splitting Up Together":
        alternate_name:
          - "Splitting Up Together US"
    - "Spongebob Squarepants"
    - "Spotless"
    # Q
    - "Squidbillies"
    - "Squinters"
    # T
    - "Stan Against Evil"
    - "Stan Lee's Lucky Man"
    - "The Stand"
    - "Star"
    - "Star Trek"
    - "Star Trek: Deep Space Nine":
        alternate_name:
          - "Star Trek: DS9"
    - "Star Trek: Discovery"
    - "Star Trek: The Animated Series"
    - "Star Trek: The Next Generation":
        alternate_name:
          - "Star Trek: TNG"
    - "Star Trek: Voyager"
    - "Star Wares: Forces of Destiny"
    - "Star Wares Resistance"
    - "Star Wars The Clone Wars"
    - "Stargate Origins"
    - "Stargate: SG1"
    - "Stargate: Universe"
    - "Stargazing Live"
    - "StarTalk":
        alternate_name:
          - "StarTalk with Neil Degrasse Tyson"
    - "StartUp"
    - "The State"
    - "States of Undress"
    - "Station 19"
    - "Stella":
        alternate_name:
          - "Stella (UK)"
    - "Steven Hawakings Grand Design"
    - "Steven Universe"
    - "Still Game"
    - "Still Open All Hours"
    - "Still Standing"
    - "Still Star Crossed"
    - "Still the King"
    - "Stitchers"
    - "Stonehenge: The Final Mystery"
    - "The Story of Diana"
    - "The Story of God with Morgan Freeman"
    - "The Story of Wales"
    - "The Strain"
    - "Strange Angel"
    - "Strange Empire"
    - "Stranger Things"
    - "Strangers"
    - "Strangers with Candy"
    - "Strike":
        alternate_name:
          - "C.B. Strike"
          - "Strike: The Career of Evil"
          - "Strike: The Cuckoos Calling"
          - "Strike: The Silkworm"
    - "Strike Back"
    - "Striking Out"
    - "Stripped"
    - "Stuck in the Middle"
    # U
    - "Suburgatory"
    - "Suburra"
    - "Succession"
    - "Suck Less with William"
    - "The Suite Life of Zack and Cody"
    - "The Suite Life on Deck"
    - "Sun Records"
    - "Sunny Day"
    - "Sunshine"
    - "Supercar Megabuild"
    - "Supercar Superbuild"
    - "Supergirl"
    - "Superior Donuts"
    - "Superjail"
    - "Supermax"
    - "Supernatural"
    - "Supernatural: The Animation"
    - "Superstition"
    - "Superstore"
    - "Survivorman"
    - "Survivors Remorse"
    - "Suspects"
    # W
    - "Swedish Dicks"
    - "Sweet Vicious"
    - "S.W.A.T."
    - "Swashbuckle"
    - "Swedish Dicks"
    - "Sweet/Vicious"
    - "Sweetbitter"
    - "Swimming"
    - "Switched at Birth"

