###

series:
  television-list:
    - "The Saboteurs"
    - "Sabrina: The Teenage Witch"
    - "Safe House"
    - "Salem"
    - "Salvation"
    - "Samurai Jack"  # 2001
    - "Santa Clarita Diet"
    - "The Sarah Jane Adventures"
    - "Saved by the Bell"
    - "Saved by the Bell: The College Years"
    - "Saving Hope"
    - "Scandal (2012)":
        alternate_name: Scandal US  # ???
    - "Schitts Creek"
    - "The Scooby-Doo Show"  # 1976
    - "Scooby-Doo & Scappy-Doo":
        alternate_name:
          - "Scooby-Doo and Scappy-Doo"
    - "Scorpion":
        alternate_name:
          - "Скорпион"
    - "Scream"
    - "Scream Queens"
    - "SEAL Team"
    - "Search Party"
    - "The Secret Adventures of Jules Verne"
    - "The Secret Life of the American Teenager"
    - "The Selection: Special Operations Experiment"
    - "Sense8"
    - "A Series of Unfortunate Events"
    - "The Seventies"
    - "Shades of Blue"
    - "Shadowhunters"
    - "The Shannara Chronicles"
    - "Sherlock"
    - "The Shield"
    - "Shinesty"
    - "Shooter"
    - "Shots Fired"
    - "Shut Eye"
    - "Sick Note"
    - "Silicon Valley"
    - "The Simpsons"
    - "The Sinner"
    - "The Sixties"
    - "Slasher"
    - "Sleepy Hollow"
    - "The Sniffer"
    - "Snowfall"
    - "Somewhere Between"
    - "The Son"
    - "The Sopranos"
    - "South of Hell"
    - "South Park"
    - "South Riding"
    - "Space's Deepest Secrets"
    - "Speechless"
    - "Spider-Man":
        alternate_name:
          - "Marvel's Spider-Man"
    - "Spongebob Squarepants"
    - "Spotless"
    - "Squidbillies"
    - "Stan Against Evil"
    - "Stan Lees Lucky Man"
    - "The Stand"
    - "Star"
    - "Star Trek: Discovery"
    - "Stargazing Live"
    - "StartUp"
    - "The State"
    - "Stella (UK)"
    - "Still the King"
    - "The Story of Diana"
    - "The Story of God with Morgan Freeman"
    - "The Strain"
    - "Stranger Things"
    - "Strike: The Cuckoos Calling"
    - "Stuck in the Middle"
    - "Sunny Day"
    - "Supercar Superbuild"
    - "Supergirl"
    - "Superior Donuts"
    - "Supermax"
    - "Supernatural"
    - "Superstore"
    - "Survivors Remorse"
    - "Swedish Dicks"
    - "Sweet Vicious"
    - "Switched at Birth"
