###

series:
  television-list:
    # A
    - "Taboo (2017)":
        alternate_name:
          - "Taboo UK"
    - "Take Two"
    - "Taken (2017)"
    - "Taken Down"
    - "Taking Fire"
    - "Tales"
    - "Tales by Light"
    - "Tales from the Crypt"
    - "Tales from the Darkside"
    - "Tales of the Gun"
    - "Tales of the Unexpected"
    - "Talespin"
    - "Tangled: The Series"
    - "Tarantula"
    - "Tarzan and Jane"
    # E
    - "Te Radar's Chequered Past"
    - "Teachers (2016)"
    - "Teen Titans"
    - "Teen Titans Go!"
    - "Teen Wolf"
    - "Teenage Mutant Ninja Turtles":
        set:
          tvdb_id: 74582
    - "Teenage Mutant Ninja Turtles (2003)":
        set:
          tvdb_id: 71032
    - "Teenage Mutant Ninja Turtles (2012)":
        set:
          tvdb_id: 261451
    - "Telenovela"
    - "Tell Me a Story"
    - "Ten Days in the Valley"
    - "Tender Touches"
    - "Tennessee Tuxedo and His Tales"
    - "Terminator: The Sarah Connor Chronicles":
        alternate_name:
          - "The Sarah Connor Chronicles"
    - "Terra Nova"
    - "Terriers"
    - "The Terror"
    - "Terry Crews Saves Christmas"
    - "Testees"
    # H
    - "Thailand: Earths Tropic Paradise"
    - "That 70s Show"
    - "That Mitchell and Webb Look"
    - "The Thick of It"
    - "The Thin Blue Line"
    - "There She Goes"
    - "ThirtySomething"
    - "This Close"
    - "This Country"
    - "This is Jinsy"
    - "This Is Us"
    - "This Isn't Working"
    - "This Old House"
    - "Thomas the Tank Engine and Friends":
        alternate_name:
          - "Thomas the Tank Engine"
    - "Those Who Can't"
    - "Three Days to Live"
    - "Three Girls"
    - "Threes Company"
    - "Threesome":
        alternate_name:
          - "Threesome (UK)"
    - "Threshold"
    - "Thriller"
    - "Through the Wormhole"
    - "Throwing Shade"
    - "Thunderbirds"
    - "Thunderbirds Are Go"
    - "Thundercats"
    # I
    - "The Tick"
    - "The Tick (2016)"
    - "Tigtone"
    - "Til Death"
    - "Tim and Eric's Bedtime Stories"
    - "Time After Time"
    - "Time Traveling Bong"
    - "Time Trax"
    - "Time Warped"
    - "Timeless"
    - "Timmy Time"
    - "Timon and Pumbaa"
    - "Tin Star"
    - "Tiny Paradise"
    - "Titans"
    # O
    - "The Tommorow People"
    - "Todd and the Book of Pure Evil"
    - "Tokyo Ghoul"
    - "Tokyo Ghoul:re"
    - "Tokyo Vampire Hotel"
    - "Tom Clancy's Jack Ryan":
        alternate_name:
          - "Jack Ryan"
    - "Tommorow When the War Began"
    - "Too Close to Home"
    - "Top Boy"
    - "Top Gear":
        alternate_name:
          - "Top Gear (UK)"
    - "Top Gear America"
    - "Top Gear (AU)"
    - "Top Gear (US)"
    - "Top of the Lake"
    - "Tosh 0"
    - "Total Bellas"
    - "Total Recall 2070"
    - "Touch"
    - "Touching Evil"
    - "Tour of Duty"
    - "En Tout Cas"
    # R
    - "Tracey Breaks the News"
    - "Tracey Ullmans Show"
    - "Tracy Beaker Returns"
    - "Trailer Park Boys"
    - "Trailer Park Boys: Out of the Park"
    - "Training Day (2017)"
    - "Transformers: Cyberverse"
    - "Transformers: Robots in Disguise"
    - "Transparent"
    - "Transporter: The Series"
    - "Trapped"
    - "Travel Man 48 Hours In"
    - "Travelers"
    - "Treehouse Masters"
    - "Treme"
    - "Trial and Error"
    - "The Triangle"
    - "The Trip"
    - "Tripped"
    - "Tripping the Rift"
    - "Trollied"
    - "Tron: Uprising"
    - "True Blood"
    - "True Detective"
    - "Trust"
    - "Trust Me"
    # U
    - "The Tunnel"
    - "TURN: Washington's Spies"
    - "TUT"
    - "Tutankhamun"
    # W
    - "The Twilight Zone"
    - "Twin Peaks"
    - "Twirlywoos"
    - "Twisted"
    - "Twisted Tales"
    - "Two and a Half Men"
    - "Two in Clover"
    - "Two Pints of Lager and a Packet of Crisps"
    # Y
    - "Typical Rick"
    - "Tyrant"

