###

series:
  television-list:
    - "Taboo (2017)":
        alternate_name:
          - "Taboo UK"
    - "Taken (2017)"
    - "Taking Fire"
    - "Tales"
    - "Tales by Light"
    - "Tales from the Crypt"
    - "Tales from the Darkside"
    - "Tales of the Gun"
    - "Talespin"
    - "Tangled: The Series"
    - "Tarzan and Jane"
    - "Te Radar's Chequered Past"
    - "Teachers (2016)"
    - "Teen Titans"
    - "Teen Titans Go!"
    - "Teen Wolf"
    - "Teenage Mutant Ninja Turtles":
        set:
          tvdb_id: 74582
    - "Teenage Mutant Ninja Turtles (2003)":
        set:
          tvdb_id: 71032
    - "Teenage Mutant Ninja Turtles (2012)":
        set:
          tvdb_id: 261451
    - "Telenovela"
    - "Terminator: The Sarah Connor Chronicles"
    - "Terra Nova"
    - "Terriers"
    - "Terry Crews Saves Christmas"
    - "Thailand: Earths Tropic Paradise"
    - "That 70s Show"
    - "The Thick of It"
    - "The Thin Blue Line"
    - "ThirtySomething"
    - "This Is Us"
    - "This Isn't Working"
    - "This Old House"
    - "Thomas the Tank Engine and Friends":
        alternate_name:
          - "Thomas the Tank Engine"
    - "Those Who Can't"
    - "Three Days to Live"
    - "Three Girls"
    - "Threes Company"
    - "Threshold"
    - "Through the Wormhole"
    - "Throwing Shade"
    - "Thunderbirds"
    - "Thunderbirds Are Go"
    - "Thundercats"
    - "The Tick"
    - "Til Death"
    - "Tim and Eric's Bedtime Stories"
    - "Time After Time"
    - "Time Traveling Bong"
    - "Time Trax"
    - "Time Warped"
    - "Timeless"
    - "Tin Star"
    - "Tiny Paradise"
    - "The Tommorow People"
    - "Todd and the Book of Pure Evil"
    - "Tommorow When the War Began"
    - "Too Close to Home"
    - "Top Boy"
    - "Top Gear"
    - "Top Gear America"
    - "Top Gear AU"
    - "Top Gear US"
    - "Top of the Lake"
    - "Tosh 0"
    - "Total Recall 2070"
    - "Touch"
    - "Tour of Duty"
    - "Tracy Beaker Returns"
    - "Trailer Park Boys"
    - "Training Day 2017"
    - "Transformers: Robots in Disguise"
    - "Transporter: The Series"
    - "Trapped"
    - "Travel Man 48 Hours In"
    - "Travelers"
    - "Trial and Error"
    - "The Triangle"
    - "The Trip"
    - "Tripped"
    - "Trollied"
    - "Tron: Uprising"
    - "True Blood"
    - "True Detective"
    - "Trust Me"
    - "The Tunnel"
    - "TURN: Washington's Spies"
    - "TUT"
    - "Tutankhamun"
    - "Twin Peaks"
    - "Twirlywoos"
    - "Twisted"
    - "Two and a Half Men"
    - "Two in Clover"
    - "Typical Rick"
    - "Tyrant"
