series:
  television-list:
    # G
    - "Ugly Americans"
    - "Ugly Betty"
    # L
    - "Ultimate Spider-Man"
    - "Ultraviolet"
    # M
    - "Umbre"
    # N
    - "Unbreakable Kimmy Schmidt"
    - "Uncle"
    - "Undateable (2014)":
        set:
          tvdb_id: 269618
    - "Under the Mountain"
    - "Underbelly"
    - "Undercover"
    - "Underground":
        set:
          tvdb_id: 300929
    - "The Undertaker"
    - "Unfabulous"
    - "Unforgotten"
    - "The Unit"
    - "The Universe"
    - "Unreal"
    - "Unsend"
    - "Unsolved Mysteries"
    - "The Unusuals"
    # P
    - "Up All Night"
    - "Upper Middle Bogan"
    - "Upstart Crow"
    # T
    - "Utopia"
    - "Utopia: In search of the Dream"

