series:
  television-list:
    - "Ugly Americans"
    - "Ugly Betty"
    - "Umbre"
    - "Unbreakable Kimmy Schmidt"
    - "Uncle"
    - "Undateable (2014)":
        set:
          tvdb_id: 269618
    - "Under the Mountain"
    - "Underbelly"
    - "Undercover"
    - "Underground":
        set:
          tvdb_id: 300929
    - "The Undertaker"
    - "Unfabulous"
    - "Unforgotten"
    - "The Unit"
    - "The Universe"
    - "Unsend"
    - "Up All Night"
    - "Upper Middle Bogan"
    - "Upstart Crow"
    - "Utopia"
    - "Utopia: In search of the Dream"
