###

series:
  television-list:
    - "V (2009)":
        set:
          tvdb_id: 94971
    # A
    - "Valor"
    - "The Vampire Diaries"
    - "Van Helsing"
    - "Vanity Fair"
    # E
    - "Veep"
    - "Vegas"
    - "Veggietales in the House"
    - "Venture"
    - "The Venture Brothers"
    - "Vera"
    - "Veritas: The Quest"
    - "Veronica Mars"
    - "Versailles"
    - "A Very Secret Service"
    # I
    - "Vice Principals"
    - "La Victima Numero 8"
    - "Victoria"
    - "Victorian Slum House"
    - "Victorious"
    - "Vikings":
        alternate_name:
          - "Викинги"  # Russian
        set:
          tvdb_id: 260449
    - "The Village"
    - "Vinyl"
    - "The VIP"
    - "Virtual Heros"
    - "The Visitor"
    - "Viva La Bam":
        set:
          tvdb_id: 73193
    - "Viva Variety"
    # O
    - "The Void"
    - "Voltron: Legendary Defender"
    - "Voyagers"
    - "Voyage to the Bottom of the Sea"

