font:
  normal:
    family: NotoSansMono NF
    style: Regular

#search:
#  matches:
#    foreground:
#    background:
#  focused_match:
#    foreground:
#    background:
#  bar:
#    background:
#    foreground:
