#!/usr/bin/env zsh

EMAIL='codyopel@gmail.com'

DOTFILES_REPO='https://github.com/codyopel/dotfiles.git'

GIT_NAME='Cody Opel'
GIT_EMAIL="${EMAIL}"

HIGH_DPI=false

RTORRENT_COLOR_PATCH=true

KRATOS_COLOR_SCHEME='monokai'

KRATOS_PROMPT='kratos'

KRATOS_PLUGINS=(
  'acdcli'
  'archive'
  'base64'
  'battery'
  'btrfs'
  'calc'
  'git'
  'golang'
  'haskell'
  'ipfs'
  'openssl'
  'pkg'
  'sprunge'
  'ssh'
  'torrent'
  'triton'
  #'user-agent'
  'volume'
  'wifi'
)

# Text editors in order of preference
KRATOS_EDITOR_PREFERENCE=("vim")

# Prevent GUI password dialog
unset SSH_ASKPASS

alias proj="cd ${HOME}/Projects"
alias root="sudo_wrap su -"
alias nixpaste="curl -F 'text=<-' http://nixpaste.noip.me"
alias youtube="youtube-dl -f "bestvideo+bestaudio" --no-check-certificate --prefer-insecure --console-title"
alias music="ncmpcpp"
alias tarxz="tar cjvf"
alias beetu='beet -c ${HOME}/.config/beets/config-unconfirmed.yaml'
