#!/usr/bin/env zsh

EMAIL='codyopel@gmail.com'

DOTFILES_REPO='https://github.com/codyopel/dotfiles.git'

GIT_NAME='Cody Opel'
GIT_EMAIL="${EMAIL}"

HIGH_DPI=false

RTORRENT_COLOR_PATCH=true

KRATOS_COLOR_SCHEME='monokai'

KRATOS_PROMPT='kratos'

KRATOS_PLUGINS=(
  'archive'
  'base64'
  'battery'
  'btrfs'
  'calc'
  'git'
  'golang'
  'haskell'
  'ipfs'
  'openssl'
  'pkg'
  'sprunge'
  #'ssh'
  'torrent'
  'triton'
  #'user-agent'
  'volume'
  'wifi'
)

# Text editors in order of preference
KRATOS_EDITOR_PREFERENCE=(
  'subl'
  'sublime'
  'mg'
)

# List jobs in long format
#setopt long_list_jobs

# recognize comments
#setopt interactivecomments

# Prevent GUI password dialog
unset SSH_ASKPASS

#if [ -d "${HOME}/.zsh/zsh-syntax-highlighting" ] ; then
#  # Load zsh-syntax-highlighting.
#  source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
#fi

#if [ -d "${HOME}/.zsh/zsh-autosuggestions" ] ; then
#  # Load zsh-autosuggestions.
#  source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
#fi

alias proj="cd ${HOME}/Projects"
alias root="sudo_wrap su -"
alias nixpaste="curl -F 'text=<-' http://nixpaste.noip.me"
alias youtube="youtube-dl --max-quality --no-check-certificate --prefer-insecure --console-title"
alias music="ncmpcpp"
alias tarxz="tar cjvf"
alias beetu='beet -c ${HOME}/.config/beets/config-unconfirmed.yaml'
