art_filename: Folder

directory: ~/Music/confimed

import:
    autotag: yes
    default_action: skip
    link: no
    move: yes
    resume: yes
    write: no
    timid: yes
    detail: yes

library: ~/.local/share/beets/library.db

match:
    #ignored: missing_tracks
    #max_rec:
    #    missing_tracks: medium
    #    unmatched_tracks: medium
    preferred:
        original_year: yes
    strong_rec_match: 0.05

musicbrainz:
    searchlimit: 10

original_year: yes

# TODO: Remove trailing underscores
# TODO: strip leading characters (dead larry as the radio)
# TODO: strip plus signs (lionize)
# TODO: strip ep in titles
# TODO: remove underscores (philip glass sym 3)
# TODO: replace ' = ' (halford = halford)

replace:
    # Replace colon space with a hyphen
    '\:\s+': '-'
    # Replace spaces with periods
    '\s+': .
    # Replace space hyphen space
    '\s+\-\s+': _
    # Replace period hyphen period
    '\.\-\.': _
    # Replace space forward-slash space
    '\s+\/\s+': _
    # Replace space under-score space
    '\s+\_\s+': _
    # Replace period under-score period
    '\.\_\.': _
    # Replace forward and backslashes
    '[\\/]': _
    # Remove commas
    '\,': ''
    # Remove apostrophes
    "'": ''
    # Remove apostrophes
    "’": ''
    # Remove exclamation points
    '\!': ''
    # Remove leading periods
    '^\.': ''
    # Remove control characters
    '[\x00-\x1f]': _
    # Remove Windows reserved characters
    '[<>"\?\*\|]': ''
    # Remove trailing periods
    '\.$': ''
    # Remove trailing whitespace
    '\s+$': ''
    # Remove leading whitespace
    '^\s+': ''
    # Combine double periods (caused by period space)
    '\.\.': .

item_fields:
    # Get ISO 3166-2 code from beets' country variable
    country_code: |
        from pycountry import countries
        # Assume that if the length of the string is <= 2 that the
        # country code is already ISO 3166-2.
        if len(country) > 2:
            # Translate common alternative spellings
            alt = {
                'Russia': 'Russian Federation'
            }
            if country.lower() == 'europe' or country.lower() == 'xe':
                # Use EU to represent European Union, does not meet the
                # criteria for inclusion in ISO 3166-1, but EU is reserved
                # for the purpose by ISO 3166/MA .
                c = 'EU'
            else:
                try:
                    c = countries.get(name=country).alpha2
                except:
                    try:
                        c = countries.get(name=alt[country]).alpha2
                    except:
                        c = country
        else:
            c = country
        return c
    #albumtype_simple: |
    #    def_types = {
    #        'example'='example'
    #    }

# beet ls -af '$albumtype $album'
# TODO: handle singletons (tracks not associated with an album)
# TODO: featured artists:
#       -add featured artists to artist or album artist tag (probably album artist)
#       -add featured artists to track title
#       -remove featured artists that are already part of the title

# TODO: artist country code with artist name
# TODO: file format, add custom function so that if flac, also include bit depth
#       and sample rate, for mp3, include mp3 type
paths:
    default: %lower{%asciify{${albumartist}/%if{${year},${year},${original_year}}_$album%if{${catalognum},_[${catalognum}]}%if{${country_code},_[${country_code}]}%if{${media},_[${media}]}%if{${albumtype},_[${albumtype}]}/${albumartist}_%if{${year},${year},${original_year}}_${album}%if{${catalognum},_[${catalognum}]}%if{${country},_[${country}]}%if{${albumtype},_[${albumtype}]}%if{${media},_[${media}]}_${track}_${title}}}
    comp: COMPILATIONS/%lower{%asciify{$album%aunique{}/${album}_%if{${original_year},${original_year},${year}}_${track}-${title}}}
    soundtrack: SOUNDTRACKS/%lower{%asciify{${album}/${album}_%if{${original_year},${original_year},${year}}_${track}-${title}}}

per_disc_numbering: no

sort_case_insensitive: yes

threaded: yes

ui:
    color: yes

write: yes

# Plugins
plugins: [
    alternatives,
    badfiles,
    chroma,
    discogs,
    embedart,
    fetchart,
    fromfilename,
    inline,
    mbsync,
    moveall,
    mpdupdate,
    scrub
]

# Plugin configuration
#acoustid:
#    apikey: AbCd1234
bpd:
    host: 127.0.0.1
    port: 6600
    volume: 100
chroma:
    auto: yes
#copyartifacts:
#    extensions: .cue .log .jpg .png
#    print_ignored: yes
embedart:
    auto: yes
    compare_threshold: 0
    ifempty: no
    maxwidth: 10000
    remove_art_file: no
fetchart:
    auto: yes
    cautious: yes
    cover_names: cover front art album folder Folder
    min_width: 800
    max_width: 10000
    enforce_ratio: no
    sources: wikipedia coverart albumart amazon
mpd:
    host: localhost
    port: 6600
    rating: no
scrub:
    auto: yes
