art_filename: Folder

directory: ~/Music

import:
    autotag: yes
    default_action: skip
    link: no
    move: yes
    resume: yes
    write: no

library: ~/.local/share/beets/library.db

match:
    #ignored: missing_tracks
    #max_rec:
    #    missing_tracks: medium
    #    unmatched_tracks: medium
    preferred:
        original_year: yes
    strong_rec_match: 0.05

musicbrainz:
    searchlimit: 10

original_year: yes

replace:
    # Replace colon space with a hyphen
    '\:\s+': '-'
    # Replace spaces with periods
    '\s+': .
    # Replace space hyphen space
    '\s+\-\s+': _
    # Replace period hyphen period
    '\.\-\.': _
    # Replace space forward-slash space
    '\s+\/\s+': _
    # Replace space under-score space
    '\s+\_\s+': _
    # Replace period under-score period
    '\.\_\.': _
    # Replace forward and backslashes
    '[\\/]': _
    # Remove commas
    '\,': ''
    # Remove apostrophes
    "'": ''
    # Remove apostrophes
    "’": ''
    # Remove exclamation points
    '\!': ''
    # Remove leading periods
    '^\.': ''
    # Remove control characters
    '[\x00-\x1f]': _
    # Remove Windows reserved characters
    '[<>"\?\*\|]': ''
    # Remove trailing periods
    '\.$': ''
    # Remove trailing whitespace
    '\s+$': ''
    # Remove leading whitespace
    '^\s+': ''
    # Combine double periods (caused by period space)
    '\.\.': .

# beet ls -af '$albumtype $album'
# TODO: handle singletons (tracks not associated with an album)
# TODO: featured artists:
#       -add featured artists to artist or album artist tag (probably album artist)
#       -add featured artists to track title
#       -remove featured artists that are already part of the title

paths:
    default: %lower{%asciify{${albumartist}/%if{${year},${year},${original_year}}_$album%if{${catalognum},_[${catalognum}]}/${albumartist}_%if{${year},${year},${original_year}}_${album}%if{${catalognum},_[${catalognum}]}_${track}_${title}}}
    albumtype:ep: %lower{%asciify{${albumartist}/%if{${year},${year},${original_year}}_$album%if{${catalognum},_[${catalognum}]}_[EP]/${albumartist}_%if{${year},${year},${original_year}}_${album}%if{${catalognum},_[${catalognum}]}_[EP]_${track}_${title}}}
    albumtype:live: %lower{%asciify{${albumartist}/%if{${year},${year},${original_year}}_$album%if{${catalognum},_[${catalognum}]}_[LIVE]/${albumartist}_%if{${year},${year},${original_year}}_${album}%if{${catalognum},_[${catalognum}]}_[LIVE]_${track}_${title}}}
    albumtype:single: %lower{%asciify{${albumartist}/%if{${year},${year},${original_year}}_$album%if{${catalognum},_[${catalognum}]}_[SINGLE]/${albumartist}_%if{${year},${year},${original_year}}_${album}%if{${catalognum},_[${catalognum}]}_[SINGLE]_${track}_${title}}}
    comp: COMPILATIONS/%lower{%asciify{$album%aunique{}/${album}_%if{${original_year},${original_year},${year}}_${track}-${title}}}
    soundtrack: SOUNDTRACKS/%lower{%asciify{${album}/${album}_%if{${original_year},${original_year},${year}}_${track}-${title}}}

per_disc_numbering: no

sort_case_insensitive: yes

threaded: yes

ui:
    color: yes

write: yes

# Plugins
plugins: badfiles chroma embedart fetchart fromfilename mbsync mpdupdate scrub

# Plugin configuration
#acoustid:
#    apikey: AbCd1234
bpd:
    host: 127.0.0.1
    port: 6600
    volume: 100
chroma:
    auto: yes
embedart:
    auto: yes
    compare_threshold: 0
    ifempty: no
    maxwidth: 10000
    remove_art_file: no
fetchart:
    auto: yes
    cautious: yes
    cover_names: cover front art album folder Folder
    min_width: 800
    max_width: 10000
    enforce_ratio: no
    remote_priority: no
    sources: wikipedia coverart albumart amazon
mpd:
    host: localhost
    port: 6600
    rating: no
scrub:
    auto: yes