art_filename: folder
directory: ~/Music
import:
    autotag: yes
    default_action: skip
    link: no
    move: yes
    resume: yes
    write: no
library: ~/.local/share/beets_database.blb
match:
    #ignored: missing_tracks
    #max_rec:
    #    missing_tracks: medium
    #    unmatched_tracks: medium
    preferred:
        original_year: yes
    strong_rec_match: 0.05
musicbrainz:
    searchlimit: 10
original_year: yes
paths:
    default: ${albumartist}/%if{${original_year},${original_year},${year}} - $album%aunique{}/${albumartist}_%if{${original_year},${original_year},${year}}_${album}_${track}-${title}_${channels}.${bitdepth}.${samplerate}
    singleton: ${albumartist}/%if{${original_year},${original_year},${year}} - $album%aunique{} [single]/${albumartist}_%if{${original_year},${original_year},${year}}_${album}_${track}_${title}_${channels}.${bitdepth}.${samplerate}
    comp: COMPILATIONS/$album%aunique{}/${album}_%if{${original_year},${original_year},${year}}_${track}-${title}_${channels}.${bitdepth}.${samplerate}
    soundtrack: SOUNDTRACKS/${album}/${album}_%if{${original_year},${original_year},${year}}_${track}-${title}_${channels}.${bitdepth}.${samplerate}
per_disc_numbering: no
sort_case_insensitive: yes
threaded: yes
ui:
    color: yes
write: yes
