ui:
    color: yes
original_year: yes
per_disc_numbering: no
write: yes
directory: ~/Music
library: ~/.local/share/beets_database.blb
import:
    move: yes
    resume: yes
    write: no
paths:
    default: ${albumartist}/${original_year} - $album%aunique{}/${albumartist}_${original_year}-${album}_${track}-${title}_${channels}.${bitdepth}.${samplerate}
    singleton: ${albumartist}/${original_year} - $album%aunique{} [single]/${albumartist}_${original_year}-${album}_${track}_${title}_${channels}.${bitdepth}.${samplerate}
    comp: COMPILATIONS/$album%aunique{}/$album_$track-$title_${channels}.${bitdepth}.${samplerate}
    soundtrack: SOUNDTRACKS/$album/$album_$track-$title_${channels}.${bitdepth}.${samplerate}
