# Flexget configuration entrypoint

# Caveats
# - free_space only supports monitoring local filesystems.
#   Need to implement a quota plugin in flexget and torrent client.

# FIXME:
# - See if there is a way to use jinja for rss paths, they are currently
#   hardcoded.
# - See if there is a way to use jinja for make_rss paths for reuse.

# Variables must be loaded first
variables: variables.yml

web_server:
  base_url: "/"
  bind: 0.0.0.0
  port: 8887
  web_ui: yes

################################## Templates ###################################

templates:
  global:
    content_size:
      min: 1  # 1MB  FIXME: does this need to be specified
      max: 200000  # 200GB
      strict: no  # Don't fail if no size is detected
    # Limit the frequency of requests to domains so they don't complain about
    # using a bot
    domain_delay:
      avistaz.to: 10 minutes
      cinemaz.to: 10 minutes
      hd-space.org: 10 minutes
      nebulance.io: 10 minutes
      pisexy.me: 10 minutes
      privatehd.to: 10 minutes
      www.torrentbytes.net: 10 minutes
      www.torrentleech.org: 10 seconds
      rss.torrentleech.org: 10 minutes
      uhdbits.org: 10 minutes
    headers:
      # TODO: write an update script using version returned by omaha-proxy
      User-Agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"
    parsing:
      movie: guessit
      series: internal  # Guessit does not support season packs
    pathscrub: linux
    #proper_movies: yes  # FIXME
    reorder_quality:
      remux:
        above: bluray  # bluray is commonly bluray rips
    retry_failed:
      retry_time: 20 seconds
      retry_time_multiplier: 2
      max_retries: 6
    verify_ssl_certificates: yes
  client:
    deluge:
      host: '{?delugeindiana.host?}'
      port: 58846
      username: '{?delugeindiana.username?}'
      password: '{?delugeindiana.password?}'
      addpaused: yes
      #label: `{{trakt_series_network}}`
      queuetotop: yes
  content-remux:
    pending_approval: yes
    regexp:
      accept:
        - remux: {from: title}
        # Only look at known groups
        - (bluhd|blupanther|blurg|epsilon|fgt|framestor|kralimarko|hdspace|hifi|hulkpower|lazy|legion|privatehd|shock): {from: title}
  content-television:
    include: [
      series/default.yml,
      #series/0.yml,
      series/1.yml,
      series/2.yml,
      series/3.yml,
      series/4.yml,
      #series/5.yml,
      series/6.yml,
      series/7.yml,
      series/8.yml,
      series/9.yml,
      series/a.yml,
      series/b.yml,
      series/c.yml,
      series/d.yml,
      series/e.yml,
      series/f.yml,
      series/g.yml,
      series/h.yml,
      series/i.yml,
      series/j.yml,
      series/k.yml,
      series/l.yml,
      series/m.yml,
      series/n.yml,
      series/o.yml,
      series/p.yml,
      series/q.yml,
      series/r.yml,
      series/s.yml,
      series/t.yml,
      series/u.yml,
      series/v.yml,
      series/w.yml,
      series/x.yml,
      series/y.yml,
      series/z.yml
    ]
    retry_failed:
      retry_time: 30 minutes
      retry_time_multiplier: 2
      max_retries: 10
    series_premiere: yes
    thetvdb_lookup: yes
  priority-1:
    #delay: none
    priority: 1
  priority-2:
    #delay: 1 hours
    priority: 2
  priority-3:
    #delay: 2 hours
    priority: 3
  priority-4:
    #delay: 3 hours
    priority: 4
  priority-5:
    #delay: 4 hours
    priority: 5
  priority-6:
    delay: 5 hours
    priority: 6
  priority-7:
    delay: 6 hours
    priority: 7
  priority-8:
    delay: 7 hours
    priority: 8
  priority-9:
    delay: 8 hours
    priority: 9
  priority-10:
    delay: 1 weeks
    pending_approval: yes
    priority: 10
  priority-20:
    delay: 2 weeks
    pending_approval: yes
    priority: 20
  priority-30:
    delay: 3 weeks
    pending_approval: yes
    priority: 20
  rss-feed:
    accept_all: yes
    # rss-* tasks only cache rss feeds to disk, make sure entries are not seen.
    seen:
      local: yes

# templates:
#   global:
#     series_lookup:
#       set:
#         tvdb_language: en
#       thetvdb_lookup: yes
#       trakt_lookup: yes
#       tvmaze_lookup: yes

#################################### Tasks #####################################

tasks:
  #
  ## Movies
  #

  movieslist-populate:
    imdb_watchlist:
      user_id: ur77836932  # FIXME: move to variables
      list: watchlist
    accept_all: yes
    list_add:
      - movie_list: imdb_movies

  # privatehd

  # scenetime

  # hd-space

  # hd4free

  # uhdbits

  #
  ## Music
  #

  # music-romanianmetaltorrents:
  #   rss:
  #     # XXX: NO HTTPS
  #     url: 'http://metal.iplay.ro/rss.php?feed=dl&passkey={?romanianmetaltorrents.passkey?}'
  #   template: [
  #     client-local,
  #     content-music,
  #     priority-1
  #   ]

  # music-metaltracker:
  #   rss:
  #     # XXX: NO HTTPS
  #     url: 'http://en.metal-tracker.com/site/rss.html'
  #   template: [
  #     client-local,
  #     content-music,
  #     priority-2
  #   ]

  #
  ## Porn
  #

  # porn-pornbay:
  #   rss:
  #     url: 'https://pornbay.org/feeds.php?feed=torrents_all&user={?pornbay.user?}&auth={?pornbay.auth?}&passkey={?pornbay.passkey?}&authkey={?pornbay.authkey?}'
  #   template: [
  #     client,
  #     content-porn,
  #     priority-1
  #   ]

  # porn-fendomcult:
  #   rss:
  #     url: 'https://femdomcult.org/feeds.php?feed=torrents_all&user={?fendomcult.user?}&auth={?fendomcult.auth?}&passkey={?fendomcult.passkey?}&authkey={?fendomcult.authkey?}'
  #   template: [
  #     client,
  #     content-porn,
  #     priority-2
  #   ]

  # porn-pornbits:
  #   priority: 2
  #   rss:
  #     url: 'https://pornbits.net/rss/{?pornbits.user?}/{?pornbits.pid?}'

  #
  ## Remux
  #

  # remux-pisexy:
  #   template: [
  #     client,
  #     content-remux,
  #     priority-1
  #   ]

  #
  ## Television
  #

  # http://showrss.info/user/51464.rss?magnets=true&namespaces=true&name=null&quality=fhd&re=yes

  television-nebulance:
    rss:
      url: file:///home/cwopel/.config/flexget/rss-nebulance.rss
    template: [
      client,
      content-television,
      priority-1
    ]

  television-hdspace:
    rss:
      url: file:///home/cwopel/.config/flexget/rss-hdspace.rss
    template: [
      client,
      content-television,
      priority-2
    ]

  television-hd4free:
    delay: 1 days  # Last resort, tracker commonly timesout
    rss:
      url: file:///home/cwopel/.config/flexget/rss-hd4free.rss
    template: [
      client,
      content-television,
      priority-3
    ]

  # television-scenetime:
  #   template: [
  #     client,
  #     content-television,
  #     priority-3
  #   ]

  television-torrentbytes:
    headers:
      Cookie: "uid={?torrentbytes.uid?}; pass={?torrentbytes.pass?}"
    rss:
      url: file:///home/cwopel/.config/flexget/rss-hd4free.rss
    template: [
      client,
      content-television,
      priority-5
    ]

  # television-worldofp2p:
  #   template: [
  #     client,
  #     content-television
  #   ]

  # television-myxz:
  #   template: [
  #     client,
  #     content-television
  #   ]

  # television-torrenting:
  #   template: [
  #     client,
  #     content-television
  #   ]

  # television-privatehd:
  #   template: [
  #     client,
  #     content-television
  #   ]

  # television-uhdbits:
  #   template: [
  #     client,
  #     content-television
  #   ]

  # television-pisexy:
  #   template: [
  #     client,
  #     content-television
  #   ]

  # television-avistaz:
  #   template: [
  #     client,
  #     content-television
  #   ]

  # television-torrentleech:
  #   discover:
  #     what:
  #       - next_series_episodes:
  #           backfill: yes
  #           from_start: yes
  #     from:
  #       - flexget_archive: [ torrentleech ]
  #   template: [
  #     client,
  #     content-television,
  #     priority-20  # Last resort to save ratio
  #   ]

  #
  ## RSS Feeds
  #

  # NOTE:
  # This caches all rss feeds, then entries are pulled from the cache.  Allows
  # for a backlog when adding new series to track that may have been previously
  # announced.

  rss-alpharatio:
    archive: [ alpharatio ]
    make_rss:
      file: ~/.config/flexget/rss-alpharatio.rss
      days: -1
    rss:
      url: 'https://alpharatio.cc/feeds.php?feed=torrents_notify_{?alpharatio.filterid?}_{?alpharatio.passkey?}&user={?alpharatio.user?}&auth={?alpharatio.auth?}&passkey={?alpharatio.passkey?}&authkey={?alpharatio.authkey?}&name={?alpharatio.name?}'
    template: [
      rss-feed
    ]

  rss-avistaz:
    archive: [ avistaz ]
    make_rss:
      file: ~/.config/flexget/rss-avistaz.rss
      days: -1
    rss:
      url: 'https://avistaz.to/rss/torrents?pid={?avistaz.pid?}'
    template: [
      rss-feed
    ]

  rss-cinemaz:
    archive: [ cinemaz ]
    make_rss:
      file: ~/.config/flexget/rss-cinemaz.rss
      days: -1
    rss:
      url: 'https://cinemaz.to/rss/torrents?pid={?cinemaz.pid?}'
    template: [
      rss-feed
    ]

  # rss-fendomcult:
  #   archive: [ fendomcult ]
  #   make_rss:
  #     file: ~/.config/flexget/rss-fendomcult.rss
  #     days: -1
  #   rss:
  #     link: enclosure
  #     url: 'https://femdomcult.org/feeds.php?feed=torrents_all&user={?fendomcult.user?}&auth={?fendomcult.auth?}&passkey={?fendomcult.passkey?}&authkey={?fendomcult.authkey?}'
  #   template: [
  #     rss-feed
  #   ]

  rss-hd4free:
    archive: [ hd4free ]
    make_rss:
      file: ~/.config/flexget/rss-hd4free.rss
      days: -1
    rss:
      url: 'https://hd4free.xyz/rss.php?type=dl&torrent_pass={?hd4free.torrent_pass?}'
    template: [
      rss-feed
    ]

  rss-hdspace:
    archive: [ hdspace ]
    make_rss:
      file: ~/.config/flexget/rss-hdspace.rss
      days: -1
    rss:
      url: 'https://hd-space.org/rss_torrents.php?feed=dl&pid={?hdspace.pid?}'
    template: [
      rss-feed
    ]

  rss-myxz:
    archive: [ myxz ]
    make_rss:
      file: ~/.config/flexget/rss-myxz.rss
      days: -1
    # XXX: Category IDs not optional
    rss:
      url: 'https://www.myxz.org/getrss.php?feed=dl&cat=3,9,17,24,7,2,8,29,10,35,38,5,22,43,44,41,45,46,15,47,48,49,50,51&passkey={?myxz.passkey?}'
    template: [
      rss-feed
    ]
    verify_ssl_certificates: no  # Redirects to cloudflare

  rss-nebulance:
    archive: [ nebulance ]
    make_rss:
      file: ~/.config/flexget/rss-nebulance.rss
      days: -1
    rss:
      url: 'https://nebulance.io/feeds.php?feed=torrents_all&user={?nebulance.user?}&auth={?nebulance.auth?}&passkey={?nebulance.passkey?}&authkey={?nebulance.authkey?}'
    template: [
      rss-feed
    ]

  rss-pisexy:
    archive: [ pisexy ]
    make_rss:
      file: ~/.config/flexget/rss-pisexy.rss
      days: -1
    rss:
      url: 'https://pisexy.me/rss.php?user={?pisexy.user?}&passkey={?pisexy.passkey?}'
    template: [
      rss-feed
    ]

  # rss-pornbay:
  #   archive: [ pornbay ]
  #   make_rss:
  #     file: ~/.config/flexget/rss-pornbay.rss
  #     days: -1
  #   rss:
  #     link: enclosure
  #     url: 'https://pornbay.org/feeds.php?feed=torrents_all&user={?pornbay.user?}&auth={?pornbay.auth?}&passkey={?pornbay.passkey?}&authkey={?pornbay.authkey?}'
  #   template: [
  #     rss-feed
  #   ]

  # FIXME: ssl cert verification failed
  # rss-pornbits:
  #   archive: [ pornbits ]
  #   make_rss:
  #     file: ~/.config/flexget/rss-pornbits.rss
  #     days: -1
  #   rss:
  #     url: 'https://pornbits.net/rss/{?pornbits.user?}/{?pornbits.pid?}'
  #   template: [
  #     rss-feed
  #   ]

  # rss-privatehd:
  #   archive: [ privatehd ]
  #   make_rss:
  #     file: ~/.config/flexget/rss-privatehd.rss
  #     days: -1
  #   rss:
  #     url: 'https://privatehd.to/rss/torrents?pid={?privatehd.pid?}'
  #   template: [
  #     rss-feed
  #   ]

  # rss-scenetime:
  #   archive: [ scenetime ]
  #   make_rss:
  #     file: ~/.config/flexget/rss-scenetime.rss
  #     days: -1
  #   # XXX: Category IDs not optional
  #   rss:
  #     url: 'https://www.scenetime.com/get_rss.php?feed=direct&user={?scenetime.user?}&cat=79,9,63,100,43,77,83,2&passkey={?scenetime.passkey?}'
  #   template: [
  #     rss-feed
  #   ]

  rss-torrentbytes:
    archive: [ torrentbytes ]
    make_rss:
      file: ~/.config/flexget/rss-torrentbytes.rss
      days: -1
    rss:
      url: 'https://www.torrentbytes.net/rss.php?passkey={?torrentbytes.passkey?}&username={?torrentbytes.username?}&limit=200&SSL=1&direct=1'
    template: [
      rss-feed
    ]

  rss-torrenting:
    archive: [ torrenting ]
    make_rss:
      file: ~/.config/flexget/rss-torrenting.rss
      days: -1
    rss:
      # XXX: Category IDs not optional
      url: 'https://www.torrenting.com/get_rss.php?feed=direct&user={?torrenting.user?}&cat=72,1,3,2,11,38,47,49,75,27,93,26,55,73,82,18,4,5,99,88,40&passkey={?torrenting.passkey?}'
    template: [
      rss-feed
    ]

  rss-torrentleech:
    archive: [ torrentleech ]
    make_rss:
      file: ~/.config/flexget/rss-torrentleech.rss
      days: -1
    rss:
      url: 'https://rss.torrentleech.org/{?torrentleech.pid?}'
    template: [
      rss-feed
    ]

  rss-uhdbits:
    archive: [ uhdbits ]
    make_rss:
      file: ~/.config/flexget/rss-uhdbits.rss
      days: -1
    rss:
      url: 'https://uhdbits.org/rss.php?action=rss&feed=dl&user={?uhdbits.user?}&passkey={?uhdbits.passkey?}&auth={?uhdbits.auth?}&authkey={?uhdbits.authkey?}'
    template: [
      rss-feed
    ]

  rss-worldofp2p:
    archive: [ worldofp2p ]
    make_rss:
      file: ~/.config/flexget/rss-worldofp2p.rss
      days: -1
    rss:
      url: 'https://www.worldofp2p.net/rss.php?type=dl&torrent_pass={?worldofp2p.torrent_pass?}'
    template: [
      rss-feed
    ]

################################## Schedules ###################################

schedules:
  - tasks: [ rss-* ]
    interval:
      minutes: 15
  - tasks: [ television-* ]
    interval:
      minutes: 10
  #- tasks: [ remux-* ]
  #  interval:
  #    minutes: 15
