#!/bin/sh

set -e

has-bin() {
    type $1 >/dev/null 2>&1
}

if ! has-bin go; then
  echo 'golang is not install, attempting installation' >&2
  if has-bin dnf; then
    sudo dnf -y install golang
  elif has-bin yum; then
    sudo yum -y install golang
  elif has-bin apt; then
    sudo apt install go
  elif has-bin apt-get; then
    sudo apt-get install go
  else
    echo 'no method to install golang' >&2
    exit 1
  fi
fi

if ! has-bin git; then
  echo 'git is not install, attempting installation' >&2
  if has-bin dnf; then
    sudo dnf -y install git
  elif has-bin yum; then
    sudo yum -y install git
  elif has-bin apt; then
    sudo apt install git
  elif has-bin apt-get; then
    sudo apt-get install git
  else
    echo 'no method to install git' >&2
    exit 1
  fi
fi
